### ISSUE TITLE
[BUG] Unable to install modules from local file

### ISSUE THREAD

**Issue by Senliast** [DerGoogler/MMRL#115]
**Describe the bug**
Unable to install any modules from local file. No matter which Magisk module i choose - it always says "(file name) does not exist".

**To Reproduce**
1. Go to the tab "installed", click the icon to install local module.
2. Choose a local module to install.

**Expected behavior**
The module should install.

**Screenshots**
![Screenshot_20240117-090904_MMRL](https://github.com/DerGoogler/MMRL/assets/23285435/1db11d39-191e-4ad5-a874-06853e13d05e)
![Screenshot_20240117-090840_MMRL](https://github.com/DerGoogler/MMRL/assets/23285435/57231b2e-d3aa-49ef-baa4-530a60f6b745)

**Device info(please complete the following information):**
 - Device: POCO F2 Pro
 - OS: crDeoid 10.1 (Android 14)
 - App Version: 1.13.9
 - User Agent: nv

**Additional context**
nv

**Comment by DerGoogler** [comment]
This issue is MMRL Install Tools related. I've released a patch to fix this issue

https://github.com/Googlers-Repo/mmrl_install_tools/releases/tag/v4.2.3

@Senliast
