### ISSUE TITLE
downloads zip but doesn't install

### ISSUE THREAD

**Issue by diehard88** [DerGoogler/MMRL#125]
as shown in screenshot.

what log files should I submit?

**Comment by DerGoogler** [comment]
Install the latest MMRL Alpha version (https://github.com/DerGoogler/MMRL/releases), also install the latest MMRL Install Tools version (https://github.com/Googlers-Repo/mmrl_install_tools/releases)

Then open MMRL -> ModFS -> (Scroll down to bottom) -> Then you'll see the explore script, replace it with:

```
<MMRLINI>/system/usr/share/mmrl/bin/mmrl_explore_install_v6
```

**Comment by diehard88** [comment]
thanks, it worked.

I already had the latest alpha and install tools versions installed. 

it was the ModFS new setting that made the difference.

thank you!

**Comment by diehard88** [comment]
one last question:    was this happening to ccbins only?

other modules installed without errors in the past.
