### ISSUE TITLE
error opening config of module mkshrc

### ISSUE THREAD

**Issue by diehard88** [DerGoogler/MMRL#128]
as seen in attached video.

**Comment by diehard88** [comment]
https://github.com/DerGoogler/MMRL/assets/25366502/e2931d37-970d-464d-90af-2f602e09c843

![SmartSelect_20240217_065722_MMRL](https://github.com/DerGoogler/MMRL/assets/25366502/122ec18d-c55e-4d1c-91fb-6d508868c793)

**Comment by DerGoogler** [comment]
That's due an error with `useNativeProperties`,  we'll migrate it to `useNativeFileStorage`>

**Comment by diehard88** [comment]
Thank you!

**Comment by diehard88** [comment]
came here just to report a different error message.

![SmartSelect_20240402_033711_MMRL](https://github.com/DerGoogler/MMRL/assets/25366502/6eca7719-4d78-48ff-bd2a-356b66e87b91)

![SmartSelect_20240402_033808_MMRL](https://github.com/DerGoogler/MMRL/assets/25366502/4ef9e891-6ae5-4e2b-b3e5-8847bde3d29d)

**Comment by DerGoogler** [comment]
> came here just to report a different error message.
> 
> ![SmartSelect_20240402_033711_MMRL](https://private-user-images.githubusercontent.com/25366502/318686490-6eca7719-4d78-48ff-bd2a-356b66e87b91.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTg5MTEsIm5iZiI6MTcxMjA1ODYxMSwicGF0aCI6Ii8yNTM2NjUwMi8zMTg2ODY0OTAtNmVjYTc3MTktNGQ3OC00OGZmLWJkMmEtMzU2YjY2ZTg3YjkxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDExNTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMmViODVjYjUxYjBhYThmMTZmMjI3MDVlNTRmNGZiMjc0MDY2Zjk2ZDY2MGQxZWI3ZDdiZmFhMThlZDgwOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8OQcvUn4oMXRnXfkvZwqTxMjKNqa5u6K6p43UJaBWM)
> 
> ![SmartSelect_20240402_033808_MMRL](https://private-user-images.githubusercontent.com/25366502/318686537-4ef9e891-6ae5-4e2b-b3e5-8847bde3d29d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTg5MTEsIm5iZiI6MTcxMjA1ODYxMSwicGF0aCI6Ii8yNTM2NjUwMi8zMTg2ODY1MzctNGVmOWU4OTEtNmFlNS00ZTJiLWIzZTUtODg0N2JkZTNkMjlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDExNTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZTk1ZTY5ZjYzMDg1YzIyZGE1OTEwOWYwZTEzMWE2NzdhMjNiMDliMzg5NzNhM2I5MmY2NGZhNzc3MGNhOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.87gU1tCADD8r7bIEfQtaJlj2Pv14v0e9Mg3QAwQcrDo)

@diehard88 , Most of the native functions are now global functions

**Comment by diehard88** [comment]
is this the same problem as described in https://github.com/DerGoogler/MMRL/issues/196?

I didn't quite get what happened there.
