### ISSUE TITLE
[BUG] Sorting in explore not all inclusive

### ISSUE THREAD

**Issue by raulvasquez** [DerGoogler/MMRL#129]
When sorting by "newest date first" in explore, the modules are not all sorted together if multiple repos are enabled and some modules are unsorted entirely. 
![Screenshot_20240222-193004_MMRL](https://github.com/DerGoogler/MMRL/assets/12431688/95a4b953-8e60-4459-9702-fa8a36542d2e)

**Comment by DerGoogler** [comment]
MRepo original format does not support sorting by date currently.

**Comment by DerGoogler** [comment]
@IzzySoft. This is currently an issue with your repo.

**Comment by IzzySoft** [comment]
@DerGoogler I'm still busy with a "big fish" here in the IzzyOnDroid F-Droid Repo – which we will hopefully "complete" this week, so I can take a "side step" to my Magisk repo then. Switching to your fork of repo-util would solve the issue then? And would it work (more or less) as a "drop-in" replacement – or what adjustments would be needed on my end? If you had a "short list of steps needed", that would be ideal – but any hints would help.

Sorry for the delay, and details about the "big fish" as soon as the changes are made public :wink:

**Comment by DerGoogler** [comment]
@IzzySoft No problem. 

There are no extra adjustments to change for my fork. 
I will keep maintaining the repo-util and won't change the current state.

**Comment by IzzySoft** [comment]
@DerGoogler thanks for your patience! I'm on it now: bad conscience for letting you wait so long made me switch some priorities – based on your "promise" it would be a drop-in replacement. Which it basically seems to be (after having installed `python3-validators`), thanks a lot for keeping it compatible! Having some questions on it, though, which I'll add to [the corresponding issue over there](https://github.com/Googlers-Repo/magisk-modules-repo-util/issues/1).
