### ISSUE TITLE
ccbins wrecking havoc

### ISSUE THREAD

**Issue by diehard88** [DerGoogler/MMRL#131]
it's the third time this happens.

I download and install ccbins.

reboot and finally go to shell and enter su.

I run ccbins to install all binaries.

Everything is installed succesfully, so I believe.

after a few minutes, root begins to behave erratically.

the shell prompt freezes, magisk app manager doesn't load up anymore, for instance.

I reboot, but device goes into a bootloop mode.

gladly I had installed the antil-bootloop module, so I can reboot successfully and get back to MMRL.     I re-enable all modules, except ccbins.

I am attaching the ccbin i installation log, because at the end of the script it does some pretty heavily stuff, for instance:

`remount_as ro
false
typeset 'arg=ro'
true
typeset 'libloc=/system/lib64'
is_mounted /system/bin
/data/adb/modules/ccbins/busybox readlink -f /system/bin
2>/dev/null 
/data/adb/modules/ccbins/busybox grep -q ' /system/bin ' /proc/mounts
return 0
/data/adb/modules/ccbins/busybox mount -o ro,remount /system/bin
is_mounted /system/etc
/data/adb/modules/ccbins/busybox readlink -f /system/etc
2>/dev/null 
/data/adb/modules/ccbins/busybox grep -q ' /system/etc ' /proc/mounts
return 0
/data/adb/modules/ccbins/busybox mount -o ro,remount /system/etc
is_mounted /system/usr
/data/adb/modules/ccbins/busybox readlink -f /system/usr
2>/dev/null 
/data/adb/modules/ccbins/busybox grep -q ' /system/usr ' /proc/mounts
return 1
is_mounted /system/usr/share
/data/adb/modules/ccbins/busybox readlink -f /system/usr/share
2>/dev/null 
/data/adb/modules/ccbins/busybox grep -q ' /system/usr/share ' /proc/mounts
return 0
/data/adb/modules/ccbins/busybox mount -o ro,remount /system/usr/share
is_mounted /system/lib64
/data/adb/modules/ccbins/busybox readlink -f /system/lib64
2>/dev/null 
/data/adb/modules/ccbins/busybox grep -q ' /system/lib64 ' /proc/mounts
return 0
/data/adb/modules/ccbins/busybox mount -o ro,remount /system/lib64
/data/adb/modules/ccbins/busybox rm -f /data/adb/modules/ccbins/tmp /data/adb/modules/ccbins/dlerror
/data/adb/modules/ccbins/busybox kill -10 27367
exit 0
`

[mmrl.config.txt](https://github.com/DerGoogler/MMRL/files/14387983/mmrl.config.txt)

[ccbins-verbose.log](https://github.com/DerGoogler/MMRL/files/14387987/ccbins-verbose.log)

**Comment by DerGoogler** [comment]
sounds like a ccbins issue 🤔
