### ISSUE TITLE
Since 2.13.9 only white on black

### ISSUE THREAD

**Issue by eku** [DerGoogler/MMRL#132]
**Describe the bug**

Sind the update to 2.13.0 background colour is black and foreground is white. The plus sign in the "add" button is white on white.

**To Reproduce**
1. Install 2.13.9
2. Move to install tab
3. See error

**Expected behavior**

Uses system theme.

**Screenshots**
![screencopy](https://github.com/DerGoogler/MMRL/assets/418685/fa456410-7b7b-4744-8d8f-f17cf05e3f41)

**Device info(please complete the following information):**
 - Device: 1+ Nord
 - OS: LOS 20
 - App Version: 2.13.9

**Additional context**

System does not use dark theme and battery save mode is turned off.

**Comment by DerGoogler** [comment]
It is supposed to be like this. Multiple themes are hard to manage.
