### ISSUE TITLE
Native `view` api not available 

### ISSUE THREAD

**Issue by DerGoogler** [DerGoogler/MMRL#133]
MMRL Install Tools logcat slider draws behind the navbar.
![Screenshot_20240224-231331](https://github.com/DerGoogler/MMRL/assets/54764558/62813c3c-ee83-42a5-b746-80445fa9122a)

> This may be a internal design bug.

**Comment by LittleDipshit** [comment]
```js
// old
const { config, setConfig } = useConfig()
// new
const [ config, setConfig, setAllConfig ] = useConfig()
```

```js
// fetch is missing
fetch("json").then((res) => res.json()).then((json) => console.log(json))
```

```js
// missing
Shell.cmd("").exec()



```

**Comment by LittleDipshit** [comment]
ModConf is also unable to handle/parse classes. To add support for class-based pages add `plugin-transform-classes`

**Comment by LittleDipshit** [comment]
- `ListSubheader` background is transparent
  - Make it default
- Make `Switch` design default

**Comment by DerGoogler** [comment]
- `ListItemDialog` remove max length
-

**Comment by DerGoogler** [comment]
Implant `FileReader`
