### ISSUE TITLE
[BUG] We hit a brick message

### ISSUE THREAD

**Issue by RichardBeisser** [DerGoogler/MMRL#155]
Hello,

I installed MMRL on a a13 LineageOS Tablet.
Device is rooted via DeltaMagisk.

When I start MMRL, I get this error message:

![Bildschirmfoto vom 2024-03-27 10-48-49](https://github.com/DerGoogler/MMRL/assets/47367173/0cb4c1c1-9674-406f-a306-f41311b6f3b1)

I also uninstalled the app, reboot device, and installed it again. Still the same

**Device info(please complete the following information):**
 - Device: TB-X605L
 - OS: a13 LOS Treble GSI
 - App Version: 2.15.10

Is there anything I can do?

Thanks.

**Comment by DerGoogler** [comment]
Did you gave the app root access?
