### ISSUE TITLE
error updating ccbins

### ISSUE THREAD

**Issue by diehard88** [DerGoogler/MMRL#156]
![SmartSelect_20240402_123807_MMRL](https://github.com/DerGoogler/MMRL/assets/25366502/19768562-18e5-4c0e-a1c9-7a54472b1a0f)

![SmartSelect_20240402_123840_MMRL](https://github.com/DerGoogler/MMRL/assets/25366502/9d5a1e76-37b6-4eb7-8a0d-6345c453c579)

**Comment by diehard88** [comment]
I removed ccbins, reboot and couldn't install ccbins.

In fact, the same happens with any module I try to install.

![Screenshot_20240402_192505_MMRL](https://github.com/DerGoogler/MMRL/assets/25366502/c30e7887-d88d-4f5d-9079-f9c75838d8af)

**Comment by DerGoogler** [comment]
This seems to be a magisk issue. KernelSU does not have any problems 🤔
