### ISSUE TITLE
[BUG] MMRL trying to use V6 script instead of V8

### ISSUE THREAD

**Issue by axujen** [DerGoogler/MMRL#170]
**Describe the bug**
MMRL trying to use V6 explore script while mmrl_install_tools is only providing the V8 script

**To Reproduce**
try to install any module and you will get the error in the screenshot

**Expected behavior**
no error

**Screenshots**
[error](https://files.catbox.moe/a4lp3t.jpeg)

**Device info(please complete the following information):**
 - Device: Redmi Note 13
 - OS: HyperOS 1.0.3
 - App Version: 2.5.12
 - User Agent: can't tell

**Additional context**
not sure if its relevant, but tapping the back key after the error doesnt work, i have to kill the app and then open it again to try again

**Comment by axujen** [comment]
sorry i forgot to title the issue, can a mod give it a title like MMRL trying to use V6 script please

**Comment by swebow** [comment]
/system/bin/sh: /data/adb/modules/mmrl_install_tools/system/usr/share/mmrl/bin/mmrl_explore_install_v6: inaccessible or not found

This is the error I get when I try to update via mmrl.

**Comment by DerGoogler** [comment]
Make sure that you set ModFS for this!

https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12

![image](https://github.com/DerGoogler/MMRL/assets/54764558/0cff89dd-45dc-430c-91f9-619923d75c55)

The latest version will it support by default.

**Comment by axujen** [comment]
> Make sure that you set ModFS for this!
> 
> https://github.com/DerGoogler/mmrl_install_tools/releases/tag/v8.5.12
> 
> ![image](https://github.com/DerGoogler/MMRL/assets/54764558/0cff89dd-45dc-430c-91f9-619923d75c55)
> 
> The latest version will it support by default.

ok this worked ty, i guess this should be closed then
