### ISSUE TITLE
New Release info popup

### ISSUE THREAD

**Issue by elhennig** [DerGoogler/MMRL#177]
**Describe the bug**
Since some days or maybe weeks I regularly get an info popup that a new version is available, 2.16.13. Even if I do have that version already installed.

**To Reproduce**
Open the app, popup appears

**Expected behavior**
Popup should not appear

**Device info(please complete the following information):**
Fairphone 4
FPOS C.0119
App Version 2.6.13

**Comment by DerGoogler** [comment]
Not really a bug. The Play Store version is newer than the GitHub variant.

**Comment by elhennig** [comment]
Yes, in the Playstore it is 2.16.14. But why does it offer 2.16.13, then?

**Comment by raulvasquez** [comment]
Will 2.16.14 be added to the GitHub releases? I use obtanium for updating most of my open source apps.

**Comment by DerGoogler** [comment]
No.

**Comment by elhennig** [comment]
So you are not willing to fix the version comparison and hence stop the new version popup from appearing, even with a newer version installed?

**Comment by DerGoogler** [comment]
> So you are not willing to fix the version comparison and hence stop the new version popup from appearing, even with a newer version installed?



> So you are not willing to fix the version comparison and hence stop the new version popup from appearing, even with a newer version installed?



> So you are not willing to fix the version comparison and hence stop the new version popup from appearing, even with a newer version installed?

No, this release was skipped for GitHub. There is a new release on GitHub
