### ISSUE TITLE
[BUG] Info not available in url install

### ISSUE THREAD

**Issue by james28909** [DerGoogler/MMRL#189]
**Describe the bug**
When I select install in mmrl, it says info not available in url install.
Unable to determine install cli. 

**To Reproduce**
I just installed the cli tool and mmrl from GitHub and it can't install modules

**Expected behavior**
I expect it to install modules

**Screenshots**
![Screenshot_20240619-123311_MMRL](https://github.com/DerGoogler/MMRL/assets/16311827/0588fb00-5eb5-4d07-a6ec-83ccb386adeb)

**Device info(please complete the following information):**
 - Device: Samsung Galaxy Note 9 N960U
 - OS: Samsung stock, rooted, android 10
 - App Version: latest
 - User Agent: not sure, I'm using edge explorer

**Additional context**
I also tried changing modfs paths but still doesn't work.

**Comment by DerGoogler** [comment]
That the info is not available with a url install is supposed. 

But why mmrl is unable to determine the install cli?

which root are you using?

**Comment by james28909** [comment]
magisk in sbin/magisk

**Comment by james28909** [comment]
just fyi, i am not sure which modfs path should be where and any help would be appreciated. it seems i had it working a while ago, but that may have been mrepo, i cant remember

**Comment by james28909** [comment]
After the update, I'm still having the same problem. Sure would like to fix it. Not much info on mmrl on Google do I really got no where else to turn. You know some things I can do to motivate this issue?

**Comment by james28909** [comment]
su -c mmrl works: 
`
` su -c mmrl
MMRL comes now as command line interface, with multi module install support!

Usage: mmrl <COMMAND>

Commands:
  upself    Update MMRL CLI
  repo      Add new repositories
  info      View module infomation
  search    Search through modules
  download  Download any module
  install   Install any module
  enable
  disable
  remove
  help      Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version

**Comment by DerGoogler** [comment]
@james28909 where is the magisk bin stored?

**Comment by james28909** [comment]
> @james28909 where is the magisk bin stored?

magisk in sbin/magisk

**Comment by DerGoogler** [comment]
```shell
ln -s /sbin/magisk /system/bin/magisk
```

**Comment by james28909** [comment]
so i need to create a symbolic link just to use the app? doesnt that seem redundant? the app should be able to find all of this on its own when launched the first time. i shouldnt need to create any links to anything just to install a module, which magisk does fine already.

**Comment by DerGoogler** [comment]
magisk does not exist in /system/bin. but mmrl cli use it fron there

**Comment by james28909** [comment]
is there some way to make mmrl cli search more paths than just /system/bin for magisk?

**Comment by james28909** [comment]
```txt
Magisk, an open-source software tool, can use the /sbin folder on Android devices to store temporary data and inject binaries into PATH. Magisk mounts a tmpfs directory to store temporary data, and if the device has an /sbin folder, Magisk will use it because it can also act as an overlay. This means that binaries like magisk, magiskinit, and symlinks to applets will be directly stored in PATH. However, if the device is running Android 11 or later, the /sbin folder may not exist, so Magisk will use /debug_ramdisk as the base folder instead. The command magisk --path can be used to determine the current base folder. 
```

**Comment by DerGoogler** [comment]
Should be fixed now. Please update to the latest MMRL-CLI release
https://github.com/DerGoogler/MMRL-CLI/releases/tag/v0.3.8
