### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Bitsonwheels** [DerGoogler/MMRL#192]
After Update to latest Version i get in any Module install try this error:

thread 'main' panicked at src/main.rs:193:36:

called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("invalid type: integer `404`, expected struct Repo", line: 1, column: 3) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Internal error!

**Comment by DerGoogler** [comment]
Show me `/adb/mmrl/repo.json`

@Bitsonwheels

**Comment by Bitsonwheels** [comment]
cat repos.json

[
        "https://raw.githubusercontent.com/ya0211/magisk-modules-alt-repo/main/json/modules.json"
]

**Comment by DerGoogler** [comment]
This repo isn't found and also not supported
