### ISSUE TITLE
[Bug] /system/bin/sh: mmrl: inaccessible or not found

### ISSUE THREAD

**Issue by HaleTom** [DerGoogler/MMRL#193]
### To Reproduce Steps to reproduce the behavior

Using Apatch.  When trying to update modules:

```
/system/bin/sh: mmrl: inaccessible or not found

Internal error!
```

### Expected behavior

Modules are updated 

### Screenshots

![Screenshot_20240629-142415_MMRL](https://github.com/DerGoogler/MMRL/assets/13854417/30eadf24-c4c4-4e09-8c12-8e5cc19e429a)

### Device

Mi 10T Pro

### OS

LineageOS 20

### App Version

2.19.18

### Root solution

APatch

**Comment by HaleTom** [comment]
It's actually here:

Add a fallback?

```
/bin $ stat /bin/sh
  File: /bin/sh
  Size: 312024          Blocks: 616        IO Block: 4096   regular file
Device: 0,42    Inode: 528         Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: ( 2000/   shell)
Access: 2024-06-12 12:29:18.288590812 +0100
Modify: 2009-01-01 00:00:00.000000000 +0000
Change: 2009-01-01 00:00:00.000000000 +0000
 Birth: -
/bin $
```

**Comment by DerGoogler** [comment]
Did you installed MMRL-CLI?

**Comment by jason-eu** [comment]
I have the same issue.

**Comment by jason-eu** [comment]
> Did you installed MMRL-CLI?

I did this after I had the exact same error on KSU and everything worked as intended after a reboot.

Thank you for the suggestion!

**Comment by diehard88** [comment]
I had the same problem.

I hadn't restarted my devices after installing these modules.     DUH!

now it's running smooth.

**Comment by lucidBrot** [comment]
I just ran into the same thing. But:
* A reboot after installing MMRL (from f-droid) does not fix it
* Attempting to install MMRL-CLI prints the same error message

```
/system/bin/sh: mmrl: inaccessible or not found
Internal error!
```

I am on Magisk 27.0, (Zygisk Yes, Ramdisk Yes), LineageOS 21 (Android 14).
Does MMRL not support my setup, or am I being slow at understanding?

MMRL version: `com.dergoogler.mmrl v2.20.20`

(Not sure if related, but the "Changelog" tab is also not working. That would be a different issue though)

**Comment by DerGoogler** [comment]
@lucidBrot try to install the latest cli version https://github.com/DerGoogler/MMRL-CLI/releases hopefully this release fixes this

**Comment by lucidBrot** [comment]
@DerGoogler Thank you for the very quick reply! 

> The initial install of mmrl-cli is through magisk

That must be what I missed. Do you think you could add that note in the error message and/or the readme?

I realize now that you do mention it in the readme under "requirements", but well... i didn't notice that it was supposed to be installed *before* the MMRL app, not *with* the app.

Tested installing another module and it worked 👍

**Comment by DerGoogler** [comment]
Keep that open, so I have a reminder and don't forget that
