### ISSUE TITLE
Systemless Mkshrc: missing `sufile`

### ISSUE THREAD

**Issue by webmaster-exit-1** [DerGoogler/MMRL#196]
### To Reproduce Steps to reproduce the behavior

Go to Installed tab;
Tap "config" for Systemless Mkshrc and received error:

### Expected behavior

I expected a configuration file to edit or maybe a drop down menu.

### Screenshots

![Screenshot_2024-07-04-03-02-59-10_fd4950220a21ab37e4313904dcdb5acb](https://github.com/DerGoogler/MMRL/assets/98633966/efd4be5b-8412-4d0f-93b7-4a5278674f63)

![Screenshot_2024-07-04-03-11-02-86_fd4950220a21ab37e4313904dcdb5acb](https://github.com/DerGoogler/MMRL/assets/98633966/b1e7b3bd-bb19-4cca-8d1c-4136693085e4)

### Device

OnePlus Nord N30 5G

### OS

OxygenOS

### App Version

14.0

### Root solution

Magisk

**Comment by webmaster-exit-1** [comment]
Just noticed this is being delt with.

**Comment by webmaster-exit-1** [comment]
if the `sufile` is new then I'll reopen

**Comment by DerGoogler** [comment]
Did you updated the module?

**Comment by DerGoogler** [comment]
@webmaster-exit-1

**Comment by webmaster-exit-1** [comment]
Hey, I'll check and update if there is one and post what happens

**Comment by webmaster-exit-1** [comment]
Oh, it was removed. Nevermind.
