### ISSUE TITLE
MMRL Install Tools; Config; Error: RenderToolbar is not a function

### ISSUE THREAD

**Issue by webmaster-exit-1** [DerGoogler/MMRL#197]
### To Reproduce Steps to reproduce the behavior

Go to "Installed" tab;
Tap "config" for MMRL Install Tools get error:
"RenderToolbar is not a function"

### Expected behavior

I expected a configuration file to edit or maybe a drop down menu.

### Screenshots

![Screenshot_2024-07-04-03-36-10-44_fd4950220a21ab37e4313904dcdb5acb](https://github.com/DerGoogler/MMRL/assets/98633966/ccec49c4-4a7f-45f2-8ed1-32de3688286e)
![Screenshot_2024-07-04-03-35-59-69_fd4950220a21ab37e4313904dcdb5acb](https://github.com/DerGoogler/MMRL/assets/98633966/3490d2c8-8eb2-4b83-8531-fedc7b281c1c)
![Screenshot_2024-07-04-03-35-05-03_fd4950220a21ab37e4313904dcdb5acb](https://github.com/DerGoogler/MMRL/assets/98633966/f4ad81c4-c9cf-4d74-8f8f-ab7bb86ea082)

### Device

OnePlus Nord N30 5G

### OS

OxygenOS

### App Version

14.0

### Root solution

Magisk

**Comment by DerGoogler** [comment]
MMRL Install Tools has been discontinued.
