### ISSUE TITLE
[Bug] thread main panic error. unable to install/update anything

### ISSUE THREAD

**Issue by JochemSKuipers** [DerGoogler/MMRL#206]
### To Reproduce Steps to reproduce the behavior

1. Try to install/update a module
2. See this error: thread 'main' panicked at src/main.rs:183:63:

called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Internal error

### Expected behavior

update/install module

### Screenshots

![Screenshot_20240719_104200](https://github.com/user-attachments/assets/866ad5f8-c5e7-47a3-b56b-362837cd902f)

### Device

RedMagic 9 pro

### OS

RedMagicOS 9.0.8 EEA

### App Version

2.20.20

### Root solution

Magisk

**Comment by JochemSKuipers** [comment]
I fixed it by reinstalling mmrl-cli, but now i get an "internal error" after every install/update and it doesnt properly install the modules

**Comment by DerGoogler** [comment]
> I fixed it by reinstalling mmrl-cli, but now i get an "internal error" after every install/update and it doesnt properly install the modules

@JochemSKuipers when you get a `Done` in the log the install was successful. **Internal error** is a known issue — I don't know from where it comes, maybe from the try-catch statement

**Comment by JochemSKuipers** [comment]
weird since when i install via mmrl and i get the internal error it doesnt install the module properly but when i download and install locally with magisk it works fine. idk if that is just an issue on my device tho

**Comment by JochemSKuipers** [comment]
i tried with updating yt revanced extended, installing mixplorer and audo mod library and all of them failed to install properly unless i installed them with magisk. and when i install from mrepo it all just works fine so it isnt that my magisk install isnt working properly

**Comment by DerGoogler** [comment]
Please grap the latest release
https://github.com/DerGoogler/MMRL-CLI/releases/tag/v0.3.10

**Comment by DerGoogler** [comment]
`/data/adb/mmrl/repos.json` is empty or doesn't exist
