### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by diehard88** [DerGoogler/MMRL#212]
![SmartSelect_20240726_054357_MMRL](https://github.com/user-attachments/assets/6147aeac-71a2-4063-a7df-86c81d9154bb)
I quite didn't get the purpose of choosing buttons.

also, why did the getevent command fail?

thanks.

**Comment by DerGoogler** [comment]
Is a not a MMRL issue. This may a issue with your rom. 

Try running `getevent` in a normal terminal

@diehard88

**Comment by diehard88** [comment]
> Is a not a MMRL issue. This may a issue with your rom.
> 
> Try running `getevent` in a normal terminal
> 
> @diehard88

I apologize I wasn't clear.

I'd like to understand buttons during module update.

the module in screenshot updated successfully and 'getevent' works fine in root terminal,

**Comment by diehard88** [comment]
cosmetic typo:     choice, not choise....

:)

**Comment by DerGoogler** [comment]
> cosmetic typo: choice, not choise....
> 
> :)

Install scripts are module related...

**Comment by DerGoogler** [comment]
https://github.com/Magisk-Modules-Alt-Repo/abootloop/blob/113594a8e62e268ebd61a01df3e2ea655114f725/customize.sh#L53

**Comment by diehard88** [comment]
alles klar danke!
