### ISSUE TITLE
Can MMRL update MMRL-cli?

### ISSUE THREAD

**Issue by lucidBrot** [DerGoogler/MMRL#220]
> The initial install of mmrl-cli is through magisk
> -- [here](https://github.com/DerGoogler/MMRL/issues/193#issuecomment-2256532143)

Does the MMRL-cli also need to be *updated* in magisk instead of in MMRL?

Because in MMRL i get this "Internal error!" when trying to upgrade from `0.3.9` to `0.3.10`:
![image](https://github.com/user-attachments/assets/4d2bcc34-0d80-41e9-b9e2-3ef744b4d840)

I am using MMRL `2.20.21`

Flashing [mmrl-cli 0.3.10](https://github.com/DerGoogler/MMRL-CLI/releases/tag/v0.3.10) in Magisk reports no error.

**Comment by lucidBrot** [comment]
Actually, might have to change this label from "question" to "bug": Even with the manually updated mmrl-cli, I get similar errors also when updating other apps.

![image](https://github.com/user-attachments/assets/42b231b9-72c7-4ac3-9a3e-24ee18bb6c31)
![image](https://github.com/user-attachments/assets/2059247d-283b-48f3-814e-de452e494ff8)

**Comment by DerGoogler** [comment]
As long `Done` is shown the install finished

**Comment by DerGoogler** [comment]
Fixed latest version.
