### ISSUE TITLE
Google Play Protect says harmful app ?

### ISSUE THREAD

**Issue by rexackermann** [DerGoogler/MMRL#221]
I know there are false positives and other stuff. But I just wanted to let you know it's flagged. If it's fixable, maybe do something about it.

**Comment by DerGoogler** [comment]
@rexackermann Did you get the app from F-Droid? If yes, it's false. This because the signature is different from mine and from the Google Play Store.

**Comment by rexackermann** [comment]
> @rexackermann Did you get the app from F-Droid? If yes, it's false. This because the signature is different from mine and from the Google Play Store.

Okay gotcha.
I used the one from release.Just wanted to make sure.Thanks for clarifying

**Comment by Shidapu** [comment]
I cant install from frdoid, only from releases here on github.
