### ISSUE TITLE
[Bug] thread 'main' panicked

### ISSUE THREAD

**Issue by elphamale** [DerGoogler/MMRL#222]
### To Reproduce Steps to reproduce the behavior

1. Go to any module page;
2. Click on 'install' or 'update'b
3. As soon as installation output screen opens see following error:
`thread 'main' panicked at src/main.rs:183:63:

called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Unknown code returned`.

MMRL-CLI is installed. If I try to install a downloaded module I get error output similar to provided above.

### Expected behavior

module installation begins

### Device

lineageos 21

### OS

lineageos 21

### App Version

mmrl 2.20.21, MMRL-CLI 0.3.10

### Root solution

Magisk

**Comment by DerGoogler** [comment]
Hey @elphamale,

please check if `/data/adb/mmrl/repos.json` has content inside. if not add a new repo with a json array format

```json
["repo"]
```

**Comment by elphamale** [comment]
I tried adding repo urls into repos.json file.

It actually installs modules but there is unusual output at the start and at the finish:

`Unable to fetch "https://gr.dergoogler.com/gmr/json/modules.json", pushed empty data

Downloading 2.3_10.zip

Downloaded 2.3_10.zip to /sdcard/Download/2.3_10.zip.zip

Info not availabe in url install

Device is system-as-root

**********************

Process Monitor Tool

by HuskyDG

**********************

*******************

Powered by Magisk

*******************

Archive: /storage/emulated/0/Download/2.3_10.zip.zip

creating: META-INF/

creating: libs/

inflating: post-fs-data.sh

inflating: customize.sh

inflating: README.md

inflating: dynmount.sh

inflating: LICENSE

creating: libs/arm64-v8a/

creating: libs/armeabi-v7a/

creating: libs/x86/

creating: libs/x86_64/

inflating: libs/x86_64/busybox

inflating: libs/x86_64/proc_monitor

inflating: libs/arm64-v8a/busybox

inflating: libs/arm64-v8a/proc_monitor

inflating: libs/x86/busybox

inflating: libs/x86/proc_monitor

inflating: libs/armeabi-v7a/busybox

inflating: libs/armeabi-v7a/proc_monitor

creating: META-INF/com/

creating: META-INF/com/google/

creating: META-INF/com/google/android/

inflating: META-INF/com/google/android/updater-script

inflating: META-INF/com/google/android/update-binary

Archive: /storage/emulated/0/Download/2.3_10.zip.zip

inflating: module.prop

Patch service: 5yu1Cfz85eJ8NXP

Install execute binary

Archive: /storage/emulated/0/Download/2.3_10.zip.zip

inflating: post-fs-data.sh

Done

Internal error!`

Also, the panik returns if I try adding third repo (izzysoft). Other two repos work fine

**Comment by DerGoogler** [comment]
Fixed latest version.
