### ISSUE TITLE
[Bug] Probably a typo!

### ISSUE THREAD

**Issue by elphamale** [DerGoogler/MMRL#224]
### To Reproduce Steps to reproduce the behavior

1. Go to any module page or update tab;
2. Click on 'install' or 'update';
3. Get the following output:
```
Downlaoding module progress: 100%

/system/bin/sh: can't open ABD: No such file or directory
```

Maybe it should it be adb?

### Expected behavior

module installation proceeds 

### Device

lineageos 21

### OS

lineageos 21

### App Version

mmrl 3.22.23, MMRL-CLI 0.3.10

### Root solution

Magisk

**Comment by DerGoogler** [comment]
Already known. I'll try to push an update today!

**Comment by stepanzak** [comment]
Also _Downlaoding_ instead of _Downloading_
