### ISSUE TITLE
download modules without root

### ISSUE THREAD

**Issue by nutpantz** [DerGoogler/MMRL#226]
Not everyone wants 50 apps with root on their device, less want apps with root running in the background all the time.

I need a module manager, not a Module supervisor. 

Root is only needed for installing modules, not for browsing or just downloading them.
Please have a root free option.

**Comment by DerGoogler** [comment]
You're right! Let's re-write the native Android code base!

No, we don't. Use the web version — mmrl.dergoogler.com. And you don't even need a app 😱
