### ISSUE TITLE
[Bug] Installation fails because file does not exist

### ISSUE THREAD

**Issue by bege10** [DerGoogler/MMRL#232]
### To Reproduce Steps to reproduce the behavior

Trying to install any module ends with this error:

```
Downloading module progress: 100%
/system/bin/sh: /data/adb/magisk/magisk32: inaccessible or not found
```

/data/adb/magisk/magisk**32** does not exist, indeed,
but there is /data/adb/magisk/magisk**64**

Because this happens with any module I suppose it might be an MMRL issue.

### Expected behavior

Install module correctly

### Device

Shiftphone 6mq (axolotl)

### OS

/e/OS-T-dev (based on LineageOS for microG,  Android 13)

### App Version

3.23.25

### Root solution

Magisk

**Comment by DerGoogler** [comment]
@bege10 that can be fixed by yourself 

Open ModFS and change it from 32 to 64
![Screenshot_20240902-015944](https://github.com/user-attachments/assets/eb39cf8b-7885-4673-b4ad-04d2c39e1d14)
