### ISSUE TITLE
[Bug] cannot install any module 

### ISSUE THREAD

**Issue by DarryDoo** [DerGoogler/MMRL#237]
### To Reproduce Steps to reproduce the behavior

Direct install OR queue and install OR local install any module 
![Screenshot_20240916-075333](https://github.com/user-attachments/assets/62616a99-956c-463b-8836-d3eeb38ade8a)

### Expected behavior

Expect module to install successfully 

### Logs

```logs
root Sep 16 10:08 .../com.termux/files/home > logcat --pid=`pidof -s com.dergoogler.mmrl` -v color
--------- beginning of main
09-16 10:09:33.799 26288 11467 D TrafficStats: tagSocket(249) with statsTag=0xffffffff, statsUid=-1
09-16 10:09:33.978 26288 11466 D TrafficStats: tagSocket(232) with statsTag=0xffffffff, statsUid=-1
09-16 10:09:36.578 26288 26295 W dergoogler.mmrl: Reducing the number of considered missed Gc histogram windows from 358 to 100
09-16 10:09:36.656 26288 26382 E NativeView:addFlag: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. Expected: main Calling: JavaBridge
09-16 10:09:36.663 26288 26288 E MMRLWebViewClient: Blocked aria-hidden on a <button> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
09-16 10:09:36.921 26288 26288 V MMRLWebViewClient: /data/local/tmp/4e65d540-7435-11ef-a63b-b977808f21a4.zip
09-16 10:09:37.135 26288 27313 D TrafficStats: tagSocket(252) with statsTag=0xffffffff, statsUid=-1
09-16 10:09:43.799 26288 26288 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
```

### Device

Pixel 7 Pro 

### OS

Stock Android 14 Sept update

### App Version

3.24.30

### Root solution

Magisk

### Additional context

Used to work until update

**Comment by DerGoogler** [comment]
@DarryDoo is that a clean installed rom?

**Comment by DerGoogler** [comment]
Open ModFS and replace the magisk install script with `/system/bin/magisk`

**Comment by DarryDoo** [comment]
Clean install roughly 4 months ago. But as stated, MMRL worked until the last update -- specifically, it worked on Sept 15.

Not sure what you want me to replace. Whole thing, or path to magisk executable?

![Screenshot_20240916-110513](https://github.com/user-attachments/assets/e4f63e2e-d19a-456d-abfc-e355647ac71a)

**Comment by DerGoogler** [comment]
@DarryDoo yes the whole thing `/system/bin/magisk --install-module "<ZIPFILE>"`

**Comment by DarryDoo** [comment]
Many thanks for the absolute banger of a quick turnaround! Works great!
