### ISSUE TITLE
[FR] Tap to copy module repo link

### ISSUE THREAD

**Issue by Damglador** [DerGoogler/MMRL#249]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MMRL

### Enhancement propose

I wasn't able to find any way to share a module with a link, and even to share it's source I have to firstly open it in browser and then copy the link in browser.

### Solution

Tap (or hold) on Source Code field in About tab to copy the link in it, maybe also aplly the same for issues field.

### Additional info

Having links like in F-Droid that lead you directly to the app page would be insanely awesome, but probably is not possible.

**Comment by DerGoogler** [comment]
Done
