### ISSUE TITLE
Dark mode hardly usable

### ISSUE THREAD

**Issue by HarriBuh** [DerGoogler/MMRL#25]
'/readable at all

![1000002092](https://github.com/DerGoogler/MMRL/assets/123186113/90881aac-02e0-4e3f-ab2d-415db24fbcd7)

Google Pixel 7
Android 13
Rooted w/ Magisk 26.1

I'm pretty sure it's due to the already dark colors of the font. Black background + dark fonts don't match well.

**Comment by DerGoogler** [comment]
Thanks for issue, I'll look into it. 👍
