### ISSUE TITLE
[FR] "Installed" label

### ISSUE THREAD

**Issue by Damglador** [DerGoogler/MMRL#250]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MMRL

### Enhancement propose

So... Its gone in V4, and it was nice to have while browsing modules.

### Solution

I guess the easiest way is to add a "Installed" tag that shows like licence now does, near it or if licence is not available just the "Installed" tag.
Or a bubble around installed version like in Droid-ify. In the list of all available modules green bubble around module version for modules with the latest version installed, orange if update is available. And just a green bubble around installed version in version list of a module, or "Installed" in a green bubble near number of the installed module.

![Screenshot_20240930-153352](https://github.com/user-attachments/assets/cce46894-d636-4ba0-a29e-78e50abecb21)
![Screenshot_20240930-153613](https://github.com/user-attachments/assets/a2cf3905-bef4-4b38-8edb-b1c628aa412a)

### Additional info

Droid-ify: https://f-droid.org/packages/com.looker.droidify/

**Comment by DerGoogler** [comment]
Is some sort of bugged
