### ISSUE TITLE
[BUG] Search dementia

### ISSUE THREAD

**Issue by Damglador** [DerGoogler/MMRL#253]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MMRL

### Bug description

Search bar clears itself after changing menu.
For example tabbing to installed modules or opening a module page in the list of repositories, makes searching pretty annoying.

### Expected behavior

Search bar keeps content and results until user clears it, or at least keeps it's content after user opens a module page.

### Actual behavior

You check full description of a module and your search bar clears itself, and you have to retype the thing.

### Steps to reproduce

1. Open app
2. Go to repository (with module list)
3. Enter something in search bar, preferably something that is a real module name
4. Tap on a module or Installed/Settings tab
5. Return to repository by closing mod's page in any way.

### UI / OS

Android

### Android Version

14

**Comment by DerGoogler** [comment]
Actually not possible with a ViewModel. (so far)

**Comment by Damglador** [comment]
Sad
