### ISSUE TITLE
Storage permissions

### ISSUE THREAD

**Issue by IzzySoft** [DerGoogler/MMRL#256]
I've just returned from my vacation and now am catching up with all the reports…

```
! repo/com.dergoogler.mmrl_32434.apk declares sensitive permission(s): android.permission.READ_EXTERNAL_STORAGE
```

Read/Write external storage was added at that point. What shall I put as reason to add the two to the app's "green list" so these do not show as warnings in the permission settings?

**Comment by DerGoogler** [comment]
The new version are based on MRepo, so basically the same as MRepo? 

It also only for Android Q and is used to download modules.

**Comment by DerGoogler** [comment]
![Screenshot_20241008-055054](https://github.com/user-attachments/assets/2037ee06-fe0e-47f1-a8fa-fe0e03b8cc85)

**Comment by IzzySoft** [comment]
> The new version are based on MRepo, so basically the same as MRepo?

Ah, hadn't that "on my radar" at that point, thanks – let me look… OK, thanks – added to the green list.
