### ISSUE TITLE
[FR] Repo Long press menu

### ISSUE THREAD

**Issue by reindex-ot** [DerGoogler/MMRL#261]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MMRL

### Enhancement propose

In the Repo admin screen, press `@` to display the menu, or you can display it by long press or menu text.

**Comment by DerGoogler** [comment]
I don't understand?
You can press `@` to open the menu.

**Comment by reindex-ot** [comment]
Add a text label to `@`

**Comment by DerGoogler** [comment]
But why it should have a label? MRepo haven't it either

**Comment by reindex-ot** [comment]
thx.
