### ISSUE TITLE
[FR] View recommended repositories

### ISSUE THREAD

**Issue by reindex-ot** [DerGoogler/MMRL#262]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MMRL

### Enhancement propose

Please implement a function to add recommended repositories to MMRL.
ex. IzzyOnDroid Magisk Repo,Magisk Modules Alt Repo...

**Comment by DerGoogler** [comment]
Those can be actually found under "Resources". 

Still learning the code base
