### ISSUE TITLE
[BUG] Restart Button Don't Work 

### ISSUE THREAD

**Issue by rimehrab** [DerGoogler/MMRL#271]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MMRL

### Bug description

Crashed when try to restart after installing a module

### Expected behavior

Restart Device 

### Actual behavior

Crashed

### UI / OS

OnePlus Oxygen OS 

### Android Version

14

**Comment by DerGoogler** [comment]
Which version do you use?

@rimehrab

**Comment by rimehrab** [comment]
@DerGoogler Latest GitHub build

**Comment by DerGoogler** [comment]
RC x build?

**Comment by DerGoogler** [comment]
https://github.com/DerGoogler/MMRL/releases/tag/v4.26.33-RC-8

**Comment by rimehrab** [comment]
@DerGoogler Latest github build 
 https://github.com/DerGoogler/MMRL/releases/tag/v4.25.33

**Comment by rimehrab** [comment]
Stable one

**Comment by DerGoogler** [comment]
in rc builds its already fixed

**Comment by rimehrab** [comment]
Ok
