### ISSUE TITLE
[FR] Maintain repo list after update

### ISSUE THREAD

**Issue by eddieofny** [DerGoogler/MMRL#278]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MMRL

### Enhancement propose

I know this was submitted as a bug and the Dev said it's not. I fail to see how, but whatever, I'll submit it as a feature request. Please add the ability to the app to maintain the repo list after updates. This really should be basic functionality as it is with the F-Droid app and all it's forks.

**Comment by Avrution** [comment]
110% this.  I see zero reason why this thing wipes out the repos when it is updated.  It makes no sense and has me about to drop using it on my devices.

**Comment by DerGoogler** [comment]
I've already said that file has been renamed where the repos are getting saved.
