### ISSUE TITLE
Can't access Support Repositories page from wiki

### ISSUE THREAD

**Issue by dhyanKaro** [DerGoogler/MMRL#282]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MMRL

### Enhancement propose

For some reason trying to click and access that hyperlink in the Resources page gives this error
`You do not have permission to update this wiki. `

**Comment by DerGoogler** [comment]
Yes, it moved to https://mmrl.dergoogler.com/repositories
