### ISSUE TITLE
[BUG] Unable to operate the module correctly in KernelSU environment.

### ISSUE THREAD

**Issue by Uiugkhbkhbkg** [DerGoogler/MMRL#290]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MMRL

### Bug description

Unable to disable normally on KernelSU, enabling the uninstall module.

### Expected behavior

When operating the module through MMRL, the module should have a correct state change after restarting.

### Actual behavior

No change.

### Steps to reproduce

Open the application, close a module, and then restart it.
Then you will magically find that the module state has not changed.

### UI / OS

MIUI

### Android Version

12

**Comment by DerGoogler** [comment]
that mostly a issue with newly updated modules

**Comment by Uiugkhbkhbkg** [comment]
> that mostly a issue with newly updated modules


https://github.com/user-attachments/assets/f5196714-5a1b-4955-b691-3f28f1dc1a87

What's the situation?
