### ISSUE TITLE
[BUG] Re-Install text label.

### ISSUE THREAD

**Issue by reindex-ot** [DerGoogler/MMRL#293]
### Checklist

- [X] No one has submitted a similar or identical bug report before
- [X] I'm using the latest version of MMRL

### Bug description

The button collapse issue has been fixed, but some of the text is still cut off.

![Screenshot_2024-12-05-16-32-57-367_com dergoogler mmrl-edit](https://github.com/user-attachments/assets/f7527e48-eb78-4334-9fca-2480369aeb71)

❌️ `再インスト` -> ⭕️ `再インストール`

### Expected behavior

adjust the width of the buttons & text label cut off.

### Actual behavior

Open app.

### UI / OS

HyperOS v1.0

### Android Version

14

**Comment by DerGoogler** [comment]
That was actually my first solution to limit the `maxLines`. I'm looking into it (again)
