### ISSUE TITLE
Is this really not a bug?

### ISSUE THREAD

**Issue by Uiugkhbkhbkg** [DerGoogler/MMRL#299]
https://github.com/user-attachments/assets/e8315129-f404-4ed3-a1d8-69161e46a792

https://github.com/user-attachments/assets/b9d28315-bb78-4e2c-ba5f-046be2c2304a

As you can see, in the two videos, one is an earlier version of MMRL, and the other is the latest release version. My device root environment is KernrlSU.It usually takes 10 seconds to operate a module in the old version, but it seems to be completed in an instant in the new version. Are you sure this is okay? I'm just curious about this question.

**Comment by DerGoogler** [comment]
Next version will include a option to choose between shell and file operation for module state change

**Restore limitations for KernelSU & APatch**

Once a module is removed in any of those environments you won't able to restore them via the app. Change to file operations and you can restore the module. It depends on how it works on YOUR system
