### ISSUE TITLE
[FR] remove module from blacklist (whitelist it) 

### ISSUE THREAD

**Issue by 50P15** [DerGoogler/MMRL#310]
### Checklist

- [X] No one has submitted a similar or identical feature request before
- [X] This suggestion does not depart from the original intention of MMRL

### Enhancement propose

Currently, is not possible to remove a module from blacklist.
I guess it's ok to have some modules blocked by default, but users should be able to whitelist them.

**Comment by DerGoogler** [comment]
Nö.
