### ISSUE TITLE
Filter for installed modules

### ISSUE THREAD

**Issue by privacyguy123** [DerGoogler/MMRL#38]
Is this a possibility in explore view?

In installed view it could be alphabetical too but mine seem to appear all over the place in random order

**Comment by DerGoogler** [comment]
![Screenshot_20230926-115402_Instagram.jpg](https://github.com/DerGoogler/MMRL/assets/54764558/3d48ef71-9609-4467-9d68-6702a6647ee2)

Filter is selectable by the red circle (via image)

**Comment by DerGoogler** [comment]
The local installed module system has been changed.

Current state: ![Screenshot_20231010-065758_MMRL Debug.png](https://github.com/DerGoogler/MMRL/assets/54764558/33a7c2f6-6bef-4621-bff0-6fcdd426803c)

> But the app facing this issue at app launch ![Screenshot_20231010-065751_MMRL Debug.png](https://github.com/DerGoogler/MMRL/assets/54764558/696710a6-302e-418e-b464-c931842d9875)
