### ISSUE TITLE
[BUG] Failure to download zip's correctly.

### ISSUE THREAD

**Issue by webmaster-exit-1** [DerGoogler/MMRL#61]
Every (but 1*) zip file downloaded (I downloaded them twice) are either corrupt or the command programmed is downloading incorrectly. All (but 1*) zip files fail. After downloading I try installing via Magisk AND via TWRP. Both times, all zip file are bad. I think whatever command MMLR uses (guessing curl or wget) is downloading an html file then naming it .zip but that's just a guess. There was 1 successful zip from the bunch I downloaded which was Kali Nethunter Firmware files*. Which helps you find the bug. Whatever was programmed in that download was correct. All others, I'm not sure. Hope this helps.

**Comment by DerGoogler** [comment]
I don't understand? Maybe a dupe. of #37
