### ISSUE TITLE
Unable to find root manager

### ISSUE THREAD

**Issue by cr24-OS** [DerGoogler/MMRL#67]
Sadly the magiskdetectionerror still exists after newest update on fresh install.

**Comment by DerGoogler** [comment]
Related to [#7](https://github.com/Googlers-Repo/mmrl_install_tools/issues/7)

**Comment by DerGoogler** [comment]
Try to run `which magisk` and see what comes.

**Comment by DerGoogler** [comment]
Try to run `which magisk` and see what comes.

**Comment by DerGoogler** [comment]
I really don't understand how this bug happens, I'm also unable to reproduce.

**Comment by DerGoogler** [comment]
You are currently the only one that is facing such an issue. I am currently unable to provide any deep bug fixes.

I want to take the last few days of this last month this year with my family and friends, so please don't expect any big updates in 2023.

**Comment by diehard88** [comment]
what is the android version of your s8?

**Comment by DerGoogler** [comment]
@cr24-OS, please check out the latest alpha and report if issue is fixed. 

MMRL V2 uses a new way to detect root in mounts

**Comment by DerGoogler** [comment]
You can find them in the release section of the repo.

**Comment by DerGoogler** [comment]
@cr24-OS , V2 is released now. Could you check if the splash screen bug and the detection error has been fixed?

**Comment by diehard88** [comment]
> @cr24-OS , V2 is released now. Could you check if the splash screen bug and the detection error has been fixed?

his case is unusual because of sbin, which was removed by google after Android 10 or 11.

**Comment by DerGoogler** [comment]
> > @cr24-OS , V2 is released now. Could you check if the splash screen bug and the detection error has been fixed?
> 
> his case is unusual because of sbin, which was removed by google after Android 10 or 11.

MMRL does not detect root by paths anymore. View [Shell.ts](https://github.com/DerGoogler/MMRL/blob/ab0ee742959b2d7bc91a36ce79471f5bc59a3335/Website/src/native/Shell.ts#L156) how it's goin' gets detected.
