### ISSUE TITLE
Can't Toggle On Dark theme

### ISSUE THREAD

**Issue by 44cK3r** [DerGoogler/MMRL#7]
I can't toggle on the Dark theme sorry thank you for this app tho Love You Keep It Up And Stay Positive

**Comment by DerGoogler** [comment]
Thanks for your report. I'll look into it!

**Comment by 44cK3r** [comment]
> Thanks for your report. I'll look into it!

All goods thank you I haven't used it in a while sorry I get bored really quickly sorry so I don't know if it has been fixed at all sorry

**Comment by 44cK3r** [comment]
Oh dang it sorry I got my last comment mixed up with another app on here with the exact same problem sorry but I do hope you can get it fixed thank you sorry

**Comment by DerGoogler** [comment]
There are currently two variants of MMRL, one is written web-based and the other based on React Native

**Comment by DerGoogler** [comment]
This isn't a issue. You need to swipe the dark mode switch.
